export const ADDON_ID = "@BRIGHTLAYER_UI/RTL_ADDON";
export const DIR_CHANGE_EVENT = `${ADDON_ID}/DIRECTION_CHANGE`;
export const DIRECTION_STORAGE_ID = `${ADDON_ID}/CURRENT_DIRECTION`;
export const PARAM_KEY = "blui-rtl";
